language: java
sudo: true
dist: trusty
jdk: oraclejdk9
addons:
  apt:
    packages:
      - oracle-java9-installer
before_install:
  - chmod +x mvnw
deploy:
  provider: heroku
  api_key: 39ade140-a578-462d-b8d9-b5860e6b52bc
  app: travis-ci-demo-rc
on:
    tags: true
    branch: travis-auto